---
config:
  flowchart:
    curve: linear
---
graph TD;
	__start__([<p>__start__</p>]):::first
	supervisor_pre(supervisor_pre)
	supervisor_post(supervisor_post)
	fetch_logs(fetch_logs)
	normalize(normalize)
	export_csv(export_csv)
	send_telegram(send_telegram)
	chunk(chunk)
	merge_results(merge_results)
	summary(summary)
	analyze(analyze)
	ti(ti)
	asset(asset)
	genrule(genrule)
	recommend(recommend)
	report(report)
	queryrag(queryrag)
	__end__([<p>__end__</p>]):::last
	__start__ --> supervisor_pre;
	analyze --> merge_results;
	asset -. &nbsp;end&nbsp; .-> __end__;
	asset -.-> genrule;
	asset -.-> queryrag;
	asset -.-> recommend;
	asset -.-> report;
	asset -. &nbsp;telegram&nbsp; .-> send_telegram;
	chunk --> analyze;
	export_csv --> supervisor_post;
	fetch_logs --> normalize;
	genrule -. &nbsp;end&nbsp; .-> __end__;
	genrule -.-> recommend;
	genrule -.-> report;
	genrule -. &nbsp;telegram&nbsp; .-> send_telegram;
	merge_results --> summary;
	normalize --> chunk;
	queryrag -. &nbsp;end&nbsp; .-> __end__;
	queryrag -.-> genrule;
	queryrag -.-> recommend;
	recommend -. &nbsp;end&nbsp; .-> __end__;
	recommend -.-> report;
	recommend -. &nbsp;telegram&nbsp; .-> send_telegram;
	report -. &nbsp;end&nbsp; .-> __end__;
	report -. &nbsp;telegram&nbsp; .-> send_telegram;
	summary --> export_csv;
	supervisor_post -. &nbsp;end&nbsp; .-> __end__;
	supervisor_post -.-> genrule;
	supervisor_post -.-> recommend;
	supervisor_post -.-> report;
	supervisor_post -. &nbsp;telegram&nbsp; .-> send_telegram;
	supervisor_post -.-> ti;
	supervisor_pre -. &nbsp;asset_query&nbsp; .-> asset;
	supervisor_pre -. &nbsp;log_analysis&nbsp; .-> fetch_logs;
	supervisor_pre -. &nbsp;generic_rule&nbsp; .-> queryrag;
	supervisor_pre -. &nbsp;ip_reputation&nbsp; .-> ti;
	ti -. &nbsp;end&nbsp; .-> __end__;
	ti -.-> asset;
	ti -.-> genrule;
	ti -.-> recommend;
	ti -.-> report;
	ti -. &nbsp;telegram&nbsp; .-> send_telegram;
	send_telegram --> __end__;
	classDef default fill:#f2f0ff,line-height:1.2
	classDef first fill-opacity:0
	classDef last fill:#bfb6fc
